### ISSUE TITLE
Fail to use the cookbook with librarian

### ISSUE THREAD

**Issue by Soulou** [higanworks-cookbooks/hwraid#4]
Hi,

I'm using librarian-chef to manage all the cookbooks we are using (https://github.com/applicationsonline/librarian-chef)

When I add this cookbook :

```
cookbook 'hwraid',
  :github => 'higanworks-cookbooks/hwraid'
```

`librarian-chef install` fails with : "Cheffile and Cheffile.lock are out of sync!" That's the only cookbook which creates an issue, do you have any idea of what could lead this issue ?

**Comment by sawanoboly** [comment]
hmm...

How about 'librarian update', or 'librarian clear' before install ?

**Comment by Soulou** [comment]
It doesn't change anything, I've already tried that..

## 

Léo Unbekandt
Student @ ENSIIE Strasbourg
+33 6 72 65 20 42
Soulou @ Twitter, Freenode, Github

**Comment by sawanoboly** [comment]
I found bug in metadata.
The librarian-chef clashed on my pc due to metadata.rb.

> /root/application_baserepo/tmp/librarian/cache/source/git/4c77978d9c5c05b9/metadata.rb:13:in `from_file': undefined method`support' for #Chef::Cookbook::Metadata:0x00000000591f50 (NoMethodError)

wrong: support
right: supports

Now, I pushed this fix to the master branch.

Could you retry please?

**Comment by sawanoboly** [comment]
Here is result of my environment using current master branch.

```
# bundle exec librarian-chef install
Installing apache2 (1.6.2)
Installing apt (1.9.2)
Installing rsyslog (1.5.0)
Installing bluepill (2.2.2)
Installing build-essential (1.4.0)
Installing openssl (1.0.2)
Installing mysql (3.0.0)
Installing ohai (1.1.8)
Installing yum (2.2.0)
Installing nginx (1.4.0)
Installing perl (1.1.0)
Installing runit (1.1.2)
Installing nginx_simplecgi (0.1.0)
Installing xml (1.1.2)
Installing php (1.1.8)
Installing nagios (4.1.0)
Installing hwraid (0.3.0)
```

**Comment by Soulou** [comment]
It works for me now, In fact it was a mistake of my own. The cookbook 
was defined twice. As the error was really unclear I hadn't seen it. I 
discovered it while using berkshelf instead of librarian. It returns a 
correct error message. Sorry for the small waste of time.

Thank you

## 

Léo Unbekandt
Student @ ENSIIE Strasbourg
+33 6 72 65 20 42
Soulou @ Twitter, Freenode, Github

**Comment by sawanoboly** [comment]
It's ok.

Thank you for your contribution!
